# appspec.yml

version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/moti-backend
    overwrite: true

hooks:
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 600
      runas: root
  ApplicationStart:
    - location: scripts/restart_server.sh
      timeout: 300
      runas: root

  ValidateService:
    - location: scripts/validate_server.sh
      timeout: 300
      runas: root
